import styles from "./styles.module.css";
import type { Metadata } from "next";
import UlPosts from "@/components/UlPosts/UlPosts";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
  keywords: "домашняя страница",
};

export default function About() {
  return (
    <div className={styles.container}>
      <UlPosts />
    </div>
  );
}
