import Link from "next/link";
import styles from "./styles.module.css";
import type { Metadata } from "next";
import next from "next";
import { revalidateTag } from "next/cache";

// export interface IPoste {
//   userId: string;
//   id: string;
//   title: string;
//   body: string;
// }

const getData = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
    next: {
      revalidate: 60,
    },
  });
  return response.json();
};

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
  keywords: "домашняя страница",
};

export default async function About() {
  const data = await getData();
  return (
    <div className={styles.container}>
      <div className={styles.box}>About</div>
      <ol className={styles.ul}>
        {data ? (
          data.map((post: any) => {
            return (
              <li className={styles.li}>
                <Link href={`/about/${post.id}`} key={post.id}>
                  {post.title}
                </Link>
              </li>
            );
          })
        ) : (
          <div>loading...</div>
        )}
      </ol>
    </div>
  );
}
