import styles from "./styles.module.css";
import React from "react";
import TeLLayout from "@/components/TeLLayout/TeLLayout";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  keywords: "домашняя страница",
};
export default function Home() {
  return (
    <div className={styles.container}>
      <TeLLayout />
    </div>
  );
}
