import styles from "./styles.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "id",
  description: "Generated by create next app",
  keywords: "Tel",
};

export default function Id() {
  return (
    <div className={styles.container}>
      <div className={styles.box}>Tel</div>
    </div>
  );
}
